### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by ShaneHudson** [ShaneHudson/ShaneHudson.Net#3]
This was one of the first responsive sites I made, so there is a lot of things wrong with it.

- [x] #2 Typography improvements - It would be nice to scale the typography for different size viewports
- [x] #4 Remove double header
- [x] #11 Header Styling
- [x] #13 Overlapping on Small Screens
